### ISSUE TITLE
Credentials file if registered with Google

### ISSUE THREAD

**Issue by DarkFighterLuke** [Shm013/certbot-dns-freenom#2]
What should I write into the credentials file if I am registered on Freenom with Google account?

**Comment by Shm013** [comment]
I also had registered with Google account. Then I set the password in freenom account and use them with account name (Email Address) from https://my.freenom.com/clientarea.php?action=details

**Comment by DarkFighterLuke** [comment]
> I also had registered with Google account. Then I set the password in freenom account and use them with account name (Email Address) from https://my.freenom.com/clientarea.php?action=details

Thank you for your reply.
I can't set up a new password because it asks for the existent one (which I haven't since I signed up using OAuth).

**Comment by Shm013** [comment]
Can you leave previous password empty? Maybe it is possible to unlink Google account from Freenom account?
All manipulations with DNS made with Freenom API help and there is no option for OAuth usage. https://www.freenom.com/en/freenom-api.html

Maybe it is possible to use cookies, but I don't know how.

**Comment by DarkFighterLuke** [comment]
> Can you leave previous password empty?
No, I can't, the previous password is mandatory.

Freenom offered service is very poor in quality and also their API and after a short research into the page I couldn't find anything about cookies or OAuth, so I think that those users have no chance to change their password (maybe contacting customer service could be useful).

Anyway, I solved my problem by simply manually doing the things that this script does (so adding TXT record and then removing it).

Thank you for your help @Shm013 !
