### ISSUE TITLE
Plugin legacy name certbot-dns-freenom:dns-freenom may be removed in a future version. Please use dns-freenom instead.

### ISSUE THREAD

**Issue by xgusto** [Shm013/certbot-dns-freenom#8]
The plugin works great, but this warning appears.
`Plugin legacy name certbot-dns-freenom:dns-freenom may be removed in a future version. Please use dns-freenom instead.`
How do I solve this?

**Comment by xgusto** [comment]
fix
credentials.ini
```
dns_freenom_username = name@email.com
dns_freenom_password = password
```


`sudo certbot certonly -a dns-freenom   --dns-freenom-credentials /path/to/credentials.ini   --dns-freenom-propagation-seconds 300   -d "*.example.com"   -m admin@example.com   --agree-tos -n `

**Comment by Shm013** [comment]
Is it working? I knew about this warning, but don't pay much attention.

Which version of certbot do you use?

I'll check this and fix instruction.

**Comment by xgusto** [comment]
Yes it works
certbot --version
`certbot 1.12.0`

credentials.ini
```
dns_freenom_username = name@email.com
dns_freenom_password = password
```

`sudo certbot certonly -a dns-freenom   --dns-freenom-credentials /path/to/credentials.ini   --dns-freenom-propagation-seconds 300   -d "*.example.com"   -m admin@example.com   --agree-tos -n `

result
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-freenom, Installer None
Requesting a certificate for *.example.com
Performing the following challenges:
dns-01 challenge for example.com
doLogin: Login successfully.
setRecord: Record added successfully
Waiting 300 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
delRecord: Record deleted successfully

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/example.com/privkey.pem
   Your certificate will expire on 2022-04-29. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again. To non-interactively renew *all* of your
   certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by Shm013** [comment]
Yes, everything fine!
I updated test and instruction.
Thank you @xgusto!
